const fs = require("node:fs");
const path = require("node:path");

// electron-builder afterPack hook.
//
// Steam's gaming mode (SteamOS Big Picture / Steam Deck) injects
//   LD_PRELOAD=.../gameoverlayrenderer.so
// into every non-Steam game it launches. That library's ELF constructor
// crashes (SIGSEGV) inside the Electron/Chromium zygote and GPU child
// processes before any JavaScript runs, so the app dies ~1s after start
// ("FATAL: zygote_host_impl_linux.cc" / "GPU process isn't usable"). An
// in-JS environment scrub is therefore useless: the crash happens before
// our code runs. The fix has to land before the Electron binary starts.
//
// So at packaging time we rename the real executable (e.g. `hydralauncher`
// -> `hydralauncher.bin`) and drop a tiny POSIX sh launcher in its place.
// The generated AppImage AppRun execs `$APPDIR/<executableName>`, which is
// now our launcher; it strips only the Steam overlay preload and execs the
// real binary. Every other LD_PRELOAD entry (e.g. mangohud) is preserved.

/**
 * Build the launcher script. `binName` is the basename of the renamed real
 * executable, which lives next to the launcher in the AppDir.
 * @param {string} binName
 * @returns {string}
 */
const buildWrapper = (binName) => `#!/bin/sh
# Hydra launch wrapper (generated by scripts/after-pack.cjs).
#
# Steam gaming mode injects LD_PRELOAD=.../gameoverlayrenderer.so into
# non-Steam games. That library's constructor SIGSEGVs inside the Electron
# zygote/GPU processes before any JS runs, killing the app on launch. We
# strip ONLY the Steam overlay entry here, before the real binary starts,
# and keep every other preload (e.g. mangohud). If nothing else remains,
# LD_PRELOAD is unset entirely. Pure POSIX sh, no external dependencies.

if [ -n "\${LD_PRELOAD+x}" ]; then
  # LD_PRELOAD entries may be separated by ':' and/or spaces. Normalise both
  # separators to newlines, drop the steam overlay, and rejoin with spaces.
  # The trailing newline on printf is required: without it, 'read' would drop
  # the final entry (it returns non-zero on an unterminated last line).
  _hydra_new_preload=$(
    printf '%s\\n' "$LD_PRELOAD" | tr ': ' '\\n\\n' | while IFS= read -r _hydra_entry; do
      [ -n "$_hydra_entry" ] || continue
      case "$_hydra_entry" in
        *gameoverlayrenderer*) ;; # drop the steam overlay preload
        *) printf '%s ' "$_hydra_entry" ;;
      esac
    done
  )
  # Trim the single trailing space left by the loop above.
  _hydra_new_preload=\${_hydra_new_preload% }

  if [ -n "$_hydra_new_preload" ]; then
    LD_PRELOAD="$_hydra_new_preload"
    export LD_PRELOAD
  else
    unset LD_PRELOAD
  fi
  unset _hydra_new_preload _hydra_entry
fi

# Resolve this script's own directory (portable, no readlink -f required) and
# exec the real Electron binary, forwarding every original argument so flags
# like --big-picture and --no-sandbox pass through untouched.
_hydra_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
exec "$_hydra_dir/${binName}" "$@"
`;

/**
 * True when the file at `filePath` is our generated sh launcher rather than
 * the real ELF binary (ELF files start with "\x7fELF", never "#!").
 * @param {string} filePath
 * @returns {boolean}
 */
const isWrapperScript = (filePath) => {
  const fd = fs.openSync(filePath, "r");
  try {
    const header = Buffer.alloc(9);
    const bytesRead = fs.readSync(fd, header, 0, header.length, 0);
    return header.subarray(0, bytesRead).toString("utf8") === "#!/bin/sh";
  } finally {
    fs.closeSync(fd);
  }
};

/**
 * @param {import("app-builder-lib").AfterPackContext} context
 */
exports.default = async function afterPack(context) {
  // Only the Linux AppImage build needs this; other platforms are untouched.
  if (context.electronPlatformName !== "linux") return;

  const { appOutDir, packager } = context;
  const executableName = packager.executableName;
  const realBinaryName = `${executableName}.bin`;

  const launcherPath = path.join(appOutDir, executableName);
  const realBinaryPath = path.join(appOutDir, realBinaryName);

  if (!fs.existsSync(launcherPath)) {
    throw new Error(
      `[after-pack] expected executable not found at ${launcherPath}`
    );
  }

  // Idempotency guard, by content rather than by the presence of the .bin
  // file: on incremental in-place rebuilds electron-builder re-copies the raw
  // binary over our launcher while a stale .bin from the previous run is still
  // around, so "does .bin exist" would skip and ship an unwrapped binary.
  if (isWrapperScript(launcherPath)) {
    console.log(
      `[after-pack] launcher already installed for ${executableName}, skipping.`
    );
    return;
  }

  // Move the real Electron binary aside (overwriting any stale .bin), then
  // install the sh launcher in its place with executable permissions.
  fs.renameSync(launcherPath, realBinaryPath);
  fs.writeFileSync(launcherPath, buildWrapper(realBinaryName), { mode: 0o755 });
  fs.chmodSync(launcherPath, 0o755);

  console.log(
    `[after-pack] installed steam-overlay-stripping launcher: ` +
      `${executableName} -> ${realBinaryName}`
  );
};
